### ISSUE TITLE
How to reproduce the results of EfficientFormer-L1.

### ISSUE THREAD

**Issue by BlueCat7** [snap-research/EfficientFormer#17]
Hi, thanks for your amazing work. And I meet some problems when I want to reproduce the accuracy 79.2 of EfficientFormer-L1. I think your result should be batch-batch is 128 and 8gpus, but I only get 77.923. And I also try more GPUs. Below are my experients:

| batch-sizes/gpus| top1 |
| ------------- | ------------- |
| 128/8  | 77.923  |
| 128/16  | 79.083  |
| 128/32  | 78.811  |

And can you give some suggestions to help me to reproduce your paper result, thanks a lot.

**Comment by liyy201912** [comment]
Hi, thanks for your interest in this work. The 79.2% accuracy of EfficientFormer-L1 is generated with batch-size = 3072 (128 over 24 GPUs), LR = 3e-3. Based on the linear scaling of LR mentioned in paper Sec. 5.1, it should similar to your 128/16 recipe with the default LR=2e-3 (accuracy 79.1%). The default LR for 2048 batch size should be okay.

In the current code release, we temporarily disable [automatic LR scaling](https://github.com/snap-research/EfficientFormer/blob/edbc27ceec7e0b429492bc5ea2afbef1bdb09bb2/main.py#L288) and use a fixed 2e-3 LR since we observe accuracy degradation when LR becomes too big or too small for some specific bs & #GPUs settings. But this might not be an optimal solution, especially for the small model - L1. We are investigating better LR scaling policies, meanwhile, we are also considering adding synchronized BN as a possible solution.

**Comment by BlueCat7** [comment]
Thanks for your detailed reply, I will check it again.
