### ISSUE TITLE
Input size must be 224x224 ?

### ISSUE THREAD

**Issue by Shudeng** [snap-research/EfficientFormer#20]
Hello, can we input images of different sizes to the model? When I change the input size as 1024x1024, it incurs some errors.

**Comment by liyy201912** [comment]
Hi Shudeng, yes, the root cause of the rigid resolution problem comes from position embeddings in ViT, which occur as attention bias in our model. 

If you want to try the model on different resolutions, it is recommended to modify the resolution in the attention module. 
https://github.com/snap-research/EfficientFormer/blob/edbc27ceec7e0b429492bc5ea2afbef1bdb09bb2/models/efficientformer.py#L33

And if flexible (nondeterministic) inference resolution is needed, you can interpolate attention bias as in our segmentation and detection model https://github.com/snap-research/EfficientFormer/blob/edbc27ceec7e0b429492bc5ea2afbef1bdb09bb2/segmentation/backbone.py#L96 

Note that we are also researching a better way to add position information with adaptive resolution.
