### ISSUE TITLE
Error in conversion from ONNX  to TFLite

### ISSUE THREAD

**Issue by TranNgocTinh0810** [snap-research/EfficientFormer#23]
I used the EfficientFormer as backbone for training a face embedding model and the accuracy was pretty good. But I tried to convert it to tflite and deploy on edge device, however, there was an error like this:
`onnx-tf - WARNING - Using the pooling op in compatibility mode. This means your graph cannot be serialized.`
This error prevents me from inference the tflite model and I don't know how to fix this, can anyone help me with this, thanks :D

**Comment by liyy201912** [comment]
Thanks for your interest in our work. We plan to release a native implementation in TF in the near future, so that exportation to TFLite can be easier. 

For a simple fix, if pooling is not well supported in the `onnx-tf` tool, you can try to replace the pool mixer with depth-wise convolution using identical kernel size (k), and initialize the weights as $$\frac{1}{k^2}$$, which is mathematically equivalent to pooling.
