### ISSUE TITLE
Latency 1.7ms for MobileNetV2 on iPhone12 seems to be inaccurate

### ISSUE THREAD

**Issue by JierunChen** [snap-research/EfficientFormer#9]
I run the MobileNetV2 on iPhone 11 with a 1.4 ms average latency. Since iPhone 12 has better ANE(NPU) resources, its latency should be even faster.

**Comment by liyy201912** [comment]
Thanks for your interest in our work. We run an extra test on another iPhone 12 (pro) and still get identical results (1.73ms). 

Let's verify: 
(1) Are you testing with MobileNetV2 x 1.0, input resolution 224x224, and run sufficient times (say 500) to take an average? 
If we look into this [repo](https://github.com/vladimir-chernykh/coreml-model-zoo/tree/master/vision/classification/mobilenet_v2), the latency on iPhone 11 (pro) is about 4 ms. 

(2) If you can actually reach 1.4ms latency, could you try EfficientFormer-L1 to see if it can also achieve a faster speed than the reported 1.6ms? It is a little bit strange though, I assume the variance introduced by device condition shouldn't be that large.

**Comment by JierunChen** [comment]
HI, thanks for the instant reply. Here's the statistic I got when benchmarking on iPhone11 with IOS 15.5 and XCode 13.4.1. The 
latency is reported by averaging 1000 runs with input resolution 224 x 224. All models are converted from torch 1.11.0+cu113 using CoreML tools (5.2.0).
![Screenshot from 2022-06-12 19-21-54](https://user-images.githubusercontent.com/42027432/173230973-6e7d4111-96ed-4f45-8dda-2daa27e73783.png)

The latency for MobileNet V2 is 1.45 ms while 5.34 for EfficientFormer-L1. It's strange. The[ repo](https://github.com/vladimir-chernykh/coreml-model-zoo/tree/master/vision/classification/mobilenet_v2) you mentioned were using an earlier version of IOS 13.5.1 and XCode 11.5, which might affect the result. Also, a recent paper [MobileOne](https://arxiv.org/abs/2206.04040) reports the latency (0.98 ms) for MobileNetV2 on iPhone 12, which is more consistent with my experimental result. Could you kindly suggest the IOS and XCode version you are using? Thanks a lot for your wonderful contribution.

**Comment by jinfagang** [comment]
@JierunChen How did tested the efficientformer speed since they are not yet release code.

**Comment by JierunChen** [comment]
> @JierunChen How did tested the efficientformer speed since they are not yet release code.

Hi, the authors already released their CoreML models with links on the homepage.

**Comment by liyy201912** [comment]
@JierunChen Hi, we finally locate the issue. Our current `MobileNetV2.mlmodel` is downloaded from [Apple model zoo](https://developer.apple.com/machine-learning/models/), which turns out to be a pretty old version. We manually export the latest mlmodel and find that MobileNetV2x1.0 runs at 1.3 ms on iPhone 12, and MobileNetV2x1.4 runs at 1.6ms. It seems that CoreML versions do have a big impact on inference speed. 

Consequently, we plan to compare EfficientFormer-L1 with MobileNetV2x1.4 instead. (79.2%@1.6ms vs. 74.7%@1.6ms)

Note that there's still a gap between our tested 1.3ms latency and the 1ms inference latency reported in Apple's MobileOne. We assume Apple may have some internal optimizations, or some [new features](https://github.com/apple/ml-ane-transformers) in ios16 revealed in WWDC 2022. We will keep monitoring Apple's compiler updates. Optimistically, EfficientFormer could possibly be faster as well with the new features. 

As for the issue of slower speed on iPhone 11, we do not have an iPhone 11 at hand at this time. But we've verified EfficientFormer on iPhone 12 &13, and it should be okay on these newer devices.

**Comment by JierunChen** [comment]
@liyy201912 Hi, I think the version of CoreML matters as it's used to convert and optimize the models. Different versions vary in supported operations. I further run experiments on iPhone 12. This time the EfficientFormer-L1 runs at a 1.6 ms latency while 1.3 ms for MobileNetV2x1.0. For MobileOne, they should have done internal optimizations as you assumed. Thanks for your clarification!
